# Cosas a limpiar

- ** Age ** -> Tiene 5120 nulos. El número es float, para la edad del cliente no es necesario
- ** job ** -> Tiene 345 nulos. CAmbiar admin. por administrative
- ** marital ** -> Esta en mayúsculas cambiar a minúsculas
- ** eduction ** -> Tiene 1807 nulos. Hay puntos separando las palabras cambiar '.' por '_'. 
- ** default ** -> Tiene 8981 nulos. Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.
- ** housing ** -> Tiene 1026 nulos. Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.
- ** loan ** -> Tiene 1026 nulos. Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.
- ** cons.price.idx ** -> Tiene 471 nulos. Cambiar a tipo float cambiando ',' por '.'.
- ** cons.conf.idx ** -> Cambiar a tipo float cambiando ',' por '.'.
- ** euribor3m ** -> Tiene 9256 nulos. Cambiar a tipo float cambiando ',' por '.'.
- ** nr.employed ** -> Cambiar a tipo integer quitando las ','.
- ** date ** -> Tiene 248 nulos. Cambiar a tipo fecha.

In [7]:
# Tratamiento de datos
import pandas as pd
pd.set_option('display.max_columns', None)
#----------------

In [9]:
df_raw = pd.read_csv('../data/bank-additional.csv')
df_raw.sample(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
42906,26865,31.0,admin.,SINGLE,university.degree,0.0,0.0,1.0,cellular,264,1,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,076","5195,8",no,17-enero-2016,29.505,-103.264,86088671-a033-44d7-8c6e-a39a4e084155
23957,24079,39.0,management,MARRIED,university.degree,0.0,1.0,0.0,telephone,204,1,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,663","5195,8",yes,13-abril-2017,29.854,-98.287,17d30dc2-0346-4ad3-95cd-33e1c87894d6
32907,33051,33.0,services,SINGLE,high.school,0.0,0.0,0.0,cellular,503,3,999,1,FAILURE,-1.8,"92,893","-46,2",NaN,"5099,1",no,23-octubre-2018,39.919,-80.014,b47741ad-4652-4a9f-b2a3-f6c4213b0ef6
14520,14617,52.0,housemaid,MARRIED,basic.4y,0.0,1.0,1.0,cellular,105,7,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,961","5228,1",no,19-diciembre-2018,47.610,-95.835,1ca620bc-6082-435d-ad0b-125f475d4005
25104,25226,54.0,admin.,DIVORCED,university.degree,0.0,1.0,1.0,cellular,355,2,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,153","5195,8",no,7-abril-2015,44.311,-110.503,c0696083-d37d-4f79-898f-8ab5299a4706

In [10]:
df = df_raw.copy()

### Cambios nombres columnas

In [17]:
df.columns = df.columns.str.replace('.','_')

In [18]:
df.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='object')

### date cambiar a formato fecha

In [25]:
meses = {
    'enero': 'January',
    'febrero': 'February',
    'marzo': 'March',
    'abril': 'April',
    'mayo': 'May',
    'junio': 'June',
    'julio': 'July',
    'agosto': 'August',
    'septiembre': 'September',
    'octubre': 'October',
    'noviembre': 'November',
    'diciembre': 'December'
}

df['date'] = df['date'].str.lower().replace(meses, regex=True)
df['date'] = pd.to_datetime(df['date'], format='%d-%B-%Y')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp_var_rate    43000 non-null  float64
 15  cons_price_idx  42529 non-null  object
 16  cons_conf_idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr_employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  datetime64[ns]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(5), object(11)
memory usage: 7.9+ MB

### marital-> Esta en mayúsculas cambiar a minúsculas

In [35]:
df['marital'] = df['marital'].str.lower()

### job-> Cambiar admin. por administrative

In [38]:
df['job'] = df['job'].str.replace('admin.', 'administrative')

### eduction -> Hay puntos separando las palabras cambiar '.' por '_'.

In [51]:
df['education']= df['education'].str.replace('.', '_')

### cons.price.idx -> Cambiar cambiar ',' por '.' y pasar a tipo float
### cons.conf.idx -> Cambiar cambiar ',' por '.' y pasar a tipo float
### euribor3m -> Cambiar cambiar ',' por '.' y pasar a tipo float

In [77]:
def comas (df, col):
    df[col] = df[col].str.replace(',', '.')
    df[col] = df[col].astype('float64')

In [80]:
comas(df,'cons_conf_idx')

### Age -> El número es float, para la edad del cliente no es necesario

In [85]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [86]:
df['age'] = df['age'].astype('Int64')

###  nr_employed -> Cambiar a tipo integer quitando las ','.

In [102]:
df['nr_employed'] = pd.to_numeric(df['nr_employed'], errors='coerce')

In [104]:
df['nr_employed'] = df['nr_employed'].round(0).astype('Int64')

### default -> Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.
### housing -> Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.
### loan -> Los valores tienen que ser 1 o 0, por lo que podemos cambiarlo de float a integer.

In [95]:
def enteros(df, col):
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].astype('Int64')

In [94]:
enteros (df, 'default')
enteros (df, 'housing')
enteros (df, 'loan')

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,latitude,longitude,id_
0,0,<NA>,housemaid,married,basic_4y,0,0,0,telephone,261,1,999,0,NONEXISTENT,1.1,93.994,-36.4,4.857,5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57,services,married,high_school,<NA>,0,0,telephone,149,1,999,0,NONEXISTENT,1.1,93.994,-36.4,NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37,services,married,high_school,0,1,0,telephone,226,1,999,0,NONEXISTENT,1.1,93.994,-36.4,4.857,5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40,administrative,married,basic_6y,0,0,0,telephone,151,1,999,0,NONEXISTENT,1.1,93.994,-36.4,NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56,services,married,high_school,0,0,1,telephone,307,1,999,0,NONEXISTENT,1.1,93.994,-36.4,NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,19154,<NA>,administrative,married,university_degree,0,0,0,cellular,618,2,999,0,NONEXISTENT,1.4,93.444,-36.1,NaN,"5228,1",yes,2015-10-13,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,26206,34,technician,married,professional_course,0,1,1,cellular,42,7,999,0,NONEXISTENT,-0.1,93.200,-42.0,NaN,"5195,8",no,2018-03-17,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,15046,<NA>,blue-collar,single,basic_6y,0,1,0,cellular,391,2,999,0,NONEXISTENT,1.4,93.918,-42.7,NaN,"5228,1",no,2016-09-15,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,15280,<NA>,administrative,married,university_degree,<NA>,0,0,cellular,674,3,999,0,NONEXISTENT,1.4,93.918,-42.7,4.958,"5228,1",no,2019-09-23,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,27570,<NA>,unemployed,single,university_degree,0,0,1,cellular,104,2,999,0,NONEXISTENT,-0.1,93.200,-42.0,4.021,"5195,8",no,2019-11-06,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  Int64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  Int64
 6   housing         41974 non-null  Int64
 7   loan            41974 non-null  Int64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp_var_rate    43000 non-null  float64
 15  cons_price_idx  42529 non-null  float64
 16  cons_conf_idx   43000 non-null  float64
 17  euribor3m       33744 non-null  float64
 18  nr_employed     43000 non-null  Int64
 19  y               43000 non-null  object
 20  date            42752 non-null  datetime64[ns]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: Int64(5), datetime64[ns](1), float64(6), int64(5), object(7)
memory usage: 8.1+ MB

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  Int64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  Int64
 6   housing         41974 non-null  Int64
 7   loan            41974 non-null  Int64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp_var_rate    43000 non-null  float64
 15  cons_price_idx  42529 non-null  float64
 16  cons_conf_idx   43000 non-null  float64
 17  euribor3m       33744 non-null  float64
 18  nr_employed     43000 non-null  Int64
 19  y               43000 non-null  object
 20  date            42752 non-null  datetime64[ns]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: Int64(5), datetime64[ns](1), float64(6), int64(5), object(7)
memory usage: 8.1+ MB

In [111]:
df.to_csv('../data/data_limpios.csv')